apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: demo
  labels:
    app: sample-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "10Mi"
              cpu: "10m"
      affinity:
        # Ensures no two pods of the same app (sample-app) are scheduled on the same node.
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # Hard requirement
            - labelSelector:
                matchLabels:
                  app: sample-app
              topologyKey: "kubernetes.io/hostname"
        # Ensures the pod runs on nodes with a specified criteria
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # Hard requirement
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: In
                     # Only schedule pods on a node labeled with 'ssd' or 'hdd'
                    values:
                      - ssd
                      - hdd