apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: demo
  labels:
    app: sample-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "10Mi"
              cpu: "10m"
      affinity:
        # Ensures the sample-app pods will only be scheduled on nodes where there is already a backend pod running.
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: backend
              topologyKey: "kubernetes.io/hostname"